le5le-com/topology

.github/workflows/generate-libs-docs.yml

```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[ ] No
```

ci: fix job error

---

libs/topology/index.ts
libs/topology/options.ts

添加禁用缩放参数
参数名你可以改，毕竟是对外api，起名要谨慎一点。

disableScale

---

libs/topology/activeLayer.ts
libs/topology/index.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
- 当前版本中，某个节点被锁定后，仍然可以缩放节点，在缩放单个节点处添加了activeLayer为状态判断条件
- 修改了锁定条件下节点的光标显示为默认光标

fix: nodes activeLayer is locked but not yet effective

---

libs/topology/activeLayer.ts
libs/topology/index.ts
libs/topology/models/line.ts
libs/topology/models/node.ts
libs/topology/models/pen.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

updateprops performance optimization

---

libs/topology/index.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Optimize the use of events

---

libs/topology/renderLayer.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feature: allow crossOrigin background image

---

libs/topology/middles/nodes/arrow.ts
libs/topology/middles/nodes/circle.ts
libs/topology/middles/nodes/cloud.ts
libs/topology/middles/nodes/cube.model.ts
libs/topology/middles/nodes/diamond.ts
libs/topology/middles/nodes/file.ts
libs/topology/middles/nodes/hexagon.ts
libs/topology/middles/nodes/image.rect.ts
libs/topology/middles/nodes/message.ts
libs/topology/middles/nodes/pentagon.ts
libs/topology/middles/nodes/pentagram.ts
libs/topology/middles/nodes/people.ts
libs/topology/middles/nodes/rectangle.ts
libs/topology/middles/nodes/text.ts
libs/topology/middles/nodes/triangle.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Rendering performance optimization

---

libs/topology/topology.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Prevent rendering blocking

---

libs/topology/options.ts
libs/topology/topology.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
add a canvas option disableMoveOutParent, disable canvas resize when pens move out parent element. keep canvas size always eqauls to parentItem size, using translate and scale to manage canvas size only.

disable canvas resize when pens move out parent element

---

libs/topology/models/pen.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

pen support visible

---

packages/core/src/models/node.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix node animation when node  the state changes

---

packages/core/src/core.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

ondrop support multi node

---

packages/core/src/models/line.ts

feat: 连线增加animateLineDash和lineJoin配置

---

packages/core/src/core.ts
packages/core/src/models/pen.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix line animation when line state change

---

packages/core/src/animateLayer.ts
packages/core/src/core.ts
packages/core/src/models/line.ts
packages/core/src/offscreen.ts
packages/core/src/renderLayer.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

animatelayer render by own

---

packages/core/src/animateLayer.ts
packages/core/src/core.ts
packages/core/src/models/line.ts
packages/core/src/offscreen.ts
packages/core/src/renderLayer.ts

Revert "animatelayer render by own"

---

packages/core/src/core.ts
packages/core/src/models/pen.ts
packages/core/src/utils/dom.ts

I don't follow those PR requirements because the official commit messages don't follow them too.

Fixes #98 #97 #96

---

packages/core/src/core.ts

Make `ondrop` public and generic, so users can use it to make their own drop behavior

Make it possible to override the default drag and drop behavior

---

packages/core/src/renderLayer.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

bkimage fill whole canvas

---

packages/core/src/core.ts
packages/core/src/models/point.ts
packages/core/src/options.ts

add disableRepeatLine option

---

packages/core/src/core.ts

```
[ ] Bugfix
[ x ] Feature
```
fix disableEmptyLine option
Issue Number: #114 
```
[ ] Yes
[ ] No
```

fix disableEmptyLine option Issues#114

---

packages/core/src/core.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix overflow

---

packages/core/package.json
packages/core/src/activeLayer.ts
packages/core/src/core.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Topology eventable support

---

packages/core/src/activeLayer.ts
packages/core/src/core.ts
packages/core/src/options.ts
packages/core/src/utils/rect.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

options support tooltip(title,markdown) config

---

.gitignore
packages/layout/src/align.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

modify:加入垂直等间距对齐+对不同选择顺序的节点进行对齐前的排序

---

packages/core/src/core.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

当cacheLen为0时不保存状态，提高显示性能

---

packages/chart-diagram/src/echarts/index.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

echarts清理缓存

---

packages/chart-diagram/src/echarts/index.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
移动echarts节点会多次触发clear()清理函数，有时会造成图表不显示异常。改为notMerge模式后问题得到解决

echarts notMerge

---

packages/class-diagram/src/class/class.rect.ts
packages/class-diagram/src/class/class.ts

class-diagram 中 简单类与类的顶部高度计算问题

简单类与类的 topHeight 计算

---

packages/core/src/core.ts
packages/core/src/offscreen.ts
packages/core/src/utils/rect.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

优化单个节点的拖拽以及整个画布的拖拽的性能

---

packages/core/src/animateLayer.ts
packages/core/src/core.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

画布移动，暂停动画，优化性能

---

packages/core/src/core.ts
packages/core/src/utils/cacheDB.ts
packages/core/src/utils/index.ts
packages/core/src/utils/rect.ts
packages/input-diagram/src/textbox/index.ts

全部的 Cache 存储到 IndexDB 中，每次 open 都会清空它。
内存中只存储 ramCaches 长度的 Cache ，用以保证正常的内存读取。

Cache 放置到 indexDB 中，内存中只存储 CacheLen 长度的缓存

---

packages/core/src/models/node.ts

先计算子节点在父节点中的位置再去构造该Node；
因为 new Node 的过程中，相当于先计算了子节点，但父节点的 rect 尚未生成！

先计算子节点在父节点中的位置再去构造该Node

---

packages/core/src/core.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

line重新连上锚点之后dispatch lineOn事件，并将操作的line的from端还是to端通过lineOnDirection传递出来

---

packages/core/src/activeLayer.ts
packages/core/src/core.ts
packages/core/src/utils/rect.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

鼠标+shift键支持单个节点，多个节点，以及组合节点的等比缩放

---

packages/core/src/activeLayer.ts
packages/core/src/core.ts
packages/core/src/utils/rect.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

获取活动区域的大小使用之前的getRect方法

---

packages/core/src/core.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

解决已有连线的锚点重现连线终点箭头不对的问题

---

packages/core/src/models/line.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

:fix: 线条的起点和终点自动关联设置(autoAnchor属性)应该从线条的from属性以及to属性中获取
